apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: tenantnamespaces.hws.io
spec:
  group: hws.io
  names:
    kind: TenantNamespace
    listKind: TenantNamespaceList
    plural: tenantnamespaces
    singular: tenantnamespace
  scope: Cluster
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: TenantNamespace is the Schema for the tenantnamespaces API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: Spec defines the desired state of TenantNamespace
            properties:
              maxCpu:
                description: MaxCpu defines the maximum CPU limit for the namespace
                type: string
              maxMemory:
                description: MaxMemory defines the maximum Memory limit for the namespace
                type: string
              maxStorage:
                description: MaxStorage defines the maximum Storage limit for the
                  namespace
                type: string
              projectId:
                description: ProjectId defines the heritage project Id
                type: string
              projectMembers:
                description: ProjectMembers defines the list of members for the project
                items:
                  type: string
                type: array
            required:
            - projectId
            - projectMembers
            - maxCpu
            - maxMemory
            - maxStorage
            type: object
          status:
            description: Status defines the observed state of TenantNamespace
            type: object
            x-kubernetes-preserve-unknown-fields: true
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: null
  storedVersions: null
