---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
  ##
  ## Custom Rules
  ##
  - apiGroups:
      - ""
    resources:
      - namespaces
      - resourcequotas
      - limitranges
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - networking.k8s.io
    resources:
      - networkpolicies
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
      #
  - apiGroups:
      - user.openshift.io
    resources:
      - groups
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
      #
  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - rolebindings
      - clusterroles
    verbs:
      - "*" # for some reason explicit list wont work
  ##
  ## Base operator rules
  ##
  - apiGroups:
      - ""
    resources:
      - secrets
      - pods
      - pods/exec
      - pods/log
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - apps
    resources:
      - deployments
      - daemonsets
      - replicasets
      - statefulsets
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  ##
  ## Rules for hws.io/v1alpha1, Kind: TenantNamespace
  ##
  - apiGroups:
      - hws.io
    resources:
      - tenantnamespaces
      - tenantnamespaces/status
      - tenantnamespaces/finalizers
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
#+kubebuilder:scaffold:rules
