# permissions for end users to view tenantnamespaces.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: tenantnamespace-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: hws-operator
    app.kubernetes.io/part-of: hws-operator
    app.kubernetes.io/managed-by: kustomize
  name: tenantnamespace-viewer-role
rules:
- apiGroups:
  - hws.io
  resources:
  - tenantnamespaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - hws.io
  resources:
  - tenantnamespaces/status
  verbs:
  - get
