apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: hws-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions: {}
  description: Heritage Web Services Operator
  displayName: Heritage Web Services Operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - heritage
  - africa
  - namespaces
  - tenant
  links:
  - name: Hws Operator
    url: https://hws-operator.domain
  maturity: alpha
  provider:
    name: heritage.africa
    url: heritage.africa
  version: 0.0.0
