apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: hws-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions: {}
  description: Additional functionality added by heritage web services.
  displayName: Heritage Web Services Operator
  icon:
  - base64data: PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiPz4KPHN2ZyBpZD0iYiIgZGF0YS1uYW1lPSJMYXllciAyIiB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAzNjkuNjcgMzQ1Ljc2Ij4KICA8ZyBpZD0iYyIgZGF0YS1uYW1lPSJpY29uIDQiPgogICAgPHBhdGggZmlsbD0iI0MxMkY0MSIgZD0iTTE1OC45OCwzNDUuNzZoNjQuNjNjLTQuNS0yNi4wNS04LjEyLTU1LjQtOS43NC04Ny41OC0yLjAyLTQwLjA3LS41My03Ni4yOCwyLjUyLTEwNy42MiwxLjk2LTEwLjQ4LDcuODYtMzMuMTUsMjcuNC00OS45NywxNi4yMy0xMy45OCwzNS43LTE4LjYsNDQuMTgtMjAuNjIsNy42NS0xLjgyLDEwLjI3LTEuNjEsMjcuMTktNC40OSwxNS4wOS0yLjU3LDI3LjMzLTUuMTYsMzUuNDItNi45OCwxMy4yNS0yLjkxLDIwLjItMTEuNCwxOC45Ni0xNi40Ni0xLjAxLTQuMTMtNy43Ni03LjE2LTE1LjcxLTcuNTctNy4yNi0uMDMtMjAuMDMsLjA3LTM1LjkyLDEuMDgtNDUuNzIsMi45MS03OC41LDEwLjkxLTgxLjA2LDMuNzQtLjI0LS42OC0uMzYtMS45MSwxLTMuOTksNi4wMy0yLjY0LDE0LjgxLTYuMTgsMjUuNjktOS40OCwyNi40Mi04LDQ0LjEyLTguMTgsNDcuNjQtMTguNDYsLjEzLS4zOSwxLjM1LTQuMS0uMjUtNy43My0yLjY5LTYuMTEtMTIuMDktOS4xOC0yMy45NS03Ljk4QzI0OS4wMy0uMDgsMjE2Ljg4LS4xOSwxOTIuNDQsLjE2Yy0zNC40MiwuNDktMTAzLjM4LDIuNjEtMTEyLjk5LDIyLjctLjY1LDEuMzYtMi41Miw1LjI3LTEsOC43MywyLjMsNS4yLDEwLjg1LDYuMSwyOC4xOCw2Ljk4LDkuMywuNDcsMjEuMjMsLjk0LDM1LjIzLDEuMTUsMS4yMiwxLjI0LDIuNjQsMy4wNCwyLjE4LDQuNTktMS4zNSw0LjUtMTcuNjEsMy4yNy0yMi4yLDIuOTlDODQuODEsNDUuMDMsMyw1NC45MiwuMDgsNzMuNDJjLS40OCwzLjA2LDEuMyw1LjYzLDEuNzYsNi4zLDEwLjExLDE0LjU5LDU4LjAzLTE3LjY3LDg3Ljc0LC40NSwuMzEsLjE5LDcuODUsNC44Niw2Ljk1LDcuODQtMS4zOCw0LjU4LTIwLjU0LTEuNzctNDAuMjgsNy41Ny0uNzgsLjM3LTE1Ljg0LDcuNjEtMTQuNzIsMTIuNTgsMS41Nyw2Ljk5LDMyLjU0LTIuMzQsNzEuMDksMTAuNzMsOC40MSwyLjg1LDI5LjEzLDEwLjE3LDQzLjEzLDI5LjYyLDMuMDQsNC4yMyw5LjE4LDEzLjc2LDE0LjI0LDQzLjcxLDYuMjcsMzcuMTEsNC40OCw2Ny41NSwzLjAzLDgzLjA0LTEuNjgsMTcuOTctNS4zOCw0Mi4zNS0xNC4wNCw3MC41MVoiLz4KICA8L2c+Cjwvc3ZnPg==
    mediatype: image/svg+xml
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - heritage
  - africa
  - namespaces
  - tenant
  links:
  - name: HWS Operator
    url: https://heritage.africa
  maturity: alpha
  provider:
    name: heritage.africa
    url: heritage.africa
  version: 0.0.0
